dist: bionic
os: linux
language: bash
addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable'
        key_url: 'https://download.docker.com/linux/ubuntu/gpg'
    update: true

env:
  global:
    - IMAGE=drpsychick/dnsmasq
    - PLATFORMS=linux/amd64,linux/arm64,linux/arm/v7,linux/arm64/v8
    - DOCKER_CLI_EXPERIMENTAL=enabled
  jobs:
    - ALPINE_VERSION=edge
    - ALPINE_VERSION=3.12
    - ALPINE_VERSION=3.11
    - ALPINE_VERSION=3.10
    - ALPINE_VERSION=3.9
    - ALPINE_VERSION=3

before_script:
  # upgrade to latest docker-ce from repo
  - sudo apt-get -y install docker-ce
  # enable experimental in docker daemon
  - docker_conf=$(sudo cat /etc/docker/daemon.json |jq '. + {"experimental":"enabled"}')
  - echo "$docker_conf" | sudo tee /etc/docker/daemon.json
  - sudo service docker start
  - docker version
  - docker buildx version
  # build the image for all platforms
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --name xbuilder --use
  - docker buildx inspect --bootstrap
  - docker buildx build --progress plain --platform $PLATFORMS --build-arg ALPINE_VERSION=$ALPINE_VERSION -t $IMAGE .
  # load a single image for local tests, see https://github.com/docker/buildx/issues/59
  - docker buildx build --progress plain --platform linux/amd64 -t $IMAGE --load .
  - export DNSMASQ_VERSION=$(docker run --rm $IMAGE --version |head -n1 |sed -e 's/Dnsmasq version \([0-9.]*\) *Copyright.*/\1/')

script:
  # test always passes
  - echo "Alpine $ALPINE_VERSION Dnsmasq $DNSMASQ_VERSION"
  - >
    echo "Running tests...";
    docker run $IMAGE --version

after_success:
  - bash deploy.sh
